const MILLSECONDS = 1

const TIME_UNIT = {
}

TIME_UNIT.s = MILLSECONDS * 1000
TIME_UNIT.m = TIME_UNIT.s * 60
TIME_UNIT.h = TIME_UNIT.m * 60
TIME_UNIT.D = TIME_UNIT.h * 24

exports.TIME_UNIT = TIME_UNIT
